# 1. 괄호

In [31]:
def solution(inputString):
    l=list(inputString)
    answer=0
    aset=set(["(","{","[","<"])
    bset=set([">","]","}",")"])
    for idx, str in enumerate(l):
        if str in aset:
            for idx2, str2 in enumerate(l[idx:]):
                if str2 in bset:
                    del(l[idx+idx2])
                    del(l[idx])
                    answer+=1
    print(l)
    for str in l:
        if str in (aset|bset):return -1
    return answer
solution("if (Count of eggs is 4.) {Buy milk.}")

IndexError: list assignment index out of range

In [13]:
inputString=">_<"

print(l)
print(i)

['>', '_', '<']
0


In [2]:
aset=set(["(","{","[","<"])
bset=set([">","]","}",")"])
aset

{'(', '<', '[', '{'}

In [7]:
l=list(inputString)
del(l[5])
l

['l', 'i', 'n', 'e', ' ', 'p', 'l', 'u', 's', ']']

In [20]:
(aset|bset)

{'(', ')', '<', '>', '[', ']', '{', '}'}

In [37]:
def solution(inputString):
    l=list(inputString)
    answer=0
    temp=0
    
    aset=set(["(","{","[","<"])
    bset=set([">","]","}",")"])
    
    for idx, str in enumerate(l):
        if str in aset:temp+=1
        if str in bset:
            temp-=1
            answer+=1
        if temp<0:return -1
    return answer
solution(">_<")

-1

# 4. 잔고

In [192]:
import pandas as pd
import numpy as np

def solution(snapshots, transactions):
    snap = pd.DataFrame(snapshots, columns=['acc','cash'])
    trans = pd.DataFrame(transactions, columns=['id','sw','acc','cash'])
    trans=trans.drop_duplicates()
    snap['cash'] = snap['cash'].apply(pd.to_numeric)
    trans[['cash','id']] = trans[['cash','id']].apply(pd.to_numeric)
    
    for idx,row in trans.iterrows():
        if len(snap.loc[snap['acc']==row['acc']]) > 0:
            if row['sw']=="SAVE" :
                snap.loc[snap['acc']==row['acc'],'cash'] += row['cash']
            else:
                snap.loc[snap['acc']==row['acc'],'cash'] -= row['cash']
        else:
            snap.loc[len(snap)] = [  row['acc'], row['cash']  ]
    snap=snap.sort_values(by='acc')
    snap.cash = snap.cash.astype('str')
    answer = snap.values.tolist()
    return answer


solution([
  ["ACCOUNT1", "100"], 
  ["ACCOUNT2", "150"]
], [
  ["1", "SAVE", "ACCOUNT2", "100"],
  ["2", "WITHDRAW", "ACCOUNT1", "50"], 
  ["1", "SAVE", "ACCOUNT2", "100"], 
  ["4", "SAVE", "ACCOUNT3", "500"], 
  ["3", "WITHDRAW", "ACCOUNT2", "30"]
])

[['ACCOUNT1', '50'], ['ACCOUNT2', '220'], ['ACCOUNT3', '500']]

In [176]:
import pandas as pd


snapshots=[
  ["ACCOUNT1", "100"], 
  ["ACCOUNT2", "150"]
]

transactions=[
  ["1", "SAVE", "ACCOUNT2", "100"],
  ["2", "WITHDRAW", "ACCOUNT1", "50"], 
  ["1", "SAVE", "ACCOUNT2", "100"], 
  ["4", "SAVE", "ACCOUNT3", "500"], 
  ["3", "WITHDRAW", "ACCOUNT2", "30"]
]

snap = pd.DataFrame(snapshots, columns=['acc','cash'])
trans = pd.DataFrame(transactions, columns=['id','sw','acc','cash'])
trans=trans.drop_duplicates()
#.sort_values(by=['id'])
#snap['cash'] = pd.to_numeric(snap['cash'])
#trans['cash'] = pd.to_numeric(trans['cash'])
snap['cash'] = snap['cash'].apply(pd.to_numeric)
trans[['cash','id']] = trans[['cash','id']].apply(pd.to_numeric)
#snapshots['account']

print(snap)
print(trans)

        acc  cash
0  ACCOUNT1   100
1  ACCOUNT2   150
   id        sw       acc  cash
0   1      SAVE  ACCOUNT2   100
1   2  WITHDRAW  ACCOUNT1    50
3   4      SAVE  ACCOUNT3   500
4   3  WITHDRAW  ACCOUNT2    30


In [155]:
snap.set_index('acc')

cash
acc           
ACCOUNT1   100
ACCOUNT2   150

In [179]:
#SUCCESS
for idx,row in trans.iterrows():
    if len(snap.loc[snap['acc']==row['acc']]) > 0:
        if row['sw']=="SAVE" :
            snap.loc[snap['acc']==row['acc'],'cash'] += row['cash']
        else:
            snap.loc[snap['acc']==row['acc'],'cash'] -= row['cash']
    else:
        snap.loc[len(snap)] = [  row['acc'], row['cash']  ]
snap=snap.sort_values(by='acc')
snap_list = snap.values.tolist()
print(snap_list)

[['ACCOUNT1', -50], ['ACCOUNT2', 360], ['ACCOUNT3', 1500]]


In [107]:
snap[snap['acc']=="ACCOUNT1"]

acc  cash
0  ACCOUNT1   100

In [117]:
snap[snap['acc']=="ACCOUNT1"]['cash']

0    100
Name: cash, dtype: int64

In [137]:
snap.loc[snap['acc']=="ACCOUNT1",'cash'] += 10
print(snap.loc[snap['acc']=="ACCOUNT1"]['cash'])

0    20
Name: cash, dtype: int64


In [ ]:
snap['cash'] = snap['cash'].

# 5. 태그

In [216]:
def solution(dataSource, tags):
    
    new=[[b[0]]+list(set(tags).intersection(b)) for b in dataSource]
#    for count, elem in sorted(  (mylist.count(e), e) for e in set(mylist), reverse=True):
    new=sorted(new, key=len, reverse=True)
    
    answer = [n[0] for n in new if len(n)>1]
    return answer[:10]
print(solution([
    ["doc1", "t1", "t2", "t3"],
    ["doc2", "t0", "t2", "t3"],
    ["doc3", "t1", "t6", "t7"],
    ["doc4", "t1", "t2", "t4"],
    ["doc5", "t6", "t100", "t8"]
],["t1", "t2", "t3"]))

['doc1', 'doc2', 'doc4', 'doc3']


---

# 2. 객관식

In [1]:
#연속된 숫자 뭉치
queue = [2,3, 6, 7, 10, 11, 12, 15, 16, 17, 21, 22, 30]

packet = []
tmp = []
v = queue.pop(0)
tmp.append(v)
print(v)
while(len(queue)>0):
    vv = queue.pop(0)
    print(vv)
    if v+1 == vv:
        tmp.append(vv)
        v = vv
    else:
        packet.append(tmp)
        tmp = []
        tmp.append(vv)
        v = vv

packet.append(tmp)

print(packet)

2
3
6
7
10
11
12
15
16
17
21
22
30
[[2, 3], [6, 7], [10, 11, 12], [15, 16, 17], [21, 22], [30]]


In [113]:
#성공
i=4
blist=[sheet[i] for sheet in sheets]

ans=answer_sheet[i]
print(blist)
print(max([b for b in blist if b != ans]),'번이 몇개?')
blist.count(max([b for b in blist if b != ans]))

['5', '3', '5', '3', '3']
5 번이 몇개?


2

In [117]:
[b if b != ans else 0 for b in blist]

['5', 0, '5', 0, 0]

In [136]:
# n 구하기까지 성공

import numpy as np
from collections import Counter

answer_sheet = "4132315142"
sheets = ["3241523133","4121314445","3243523133","4433325251","2412313253"]
n=nmax=0
mrx=np.zeros((len(sheets),len(answer_sheet)))

for i in range(len(answer_sheet)):  # i번째 문제
    blist=[sheet[i] for sheet in sheets]
    mrx[:,i] = [b if b != answer_sheet[i] else 0 for b in blist]
    
    mode=Counter(mrx[:,i]).most_common()
    if mode[0][1] >= 2 and mode[0][0] != 0: n+=1 # 중복되는 오답이 있으면
    

print(mrx)
print(n) # 총 의심문항의 수

[[3. 2. 4. 1. 5. 2. 3. 0. 3. 3.]
 [0. 0. 2. 1. 0. 0. 4. 4. 0. 5.]
 [3. 2. 4. 3. 5. 2. 3. 0. 3. 3.]
 [0. 4. 0. 3. 0. 2. 0. 2. 5. 1.]
 [2. 4. 1. 0. 0. 0. 3. 2. 5. 3.]]
8


In [ ]:
for i in range(len(mrx[0])) : # i번째 문제
    for j in range(len(mrx))-[j] : # j번째 사람
        mrx[]

In [145]:
print(list(range(3)).remove(1))

[0, 1, 2]


# 3. 도로

In [ ]:
def solution(road, n):
    answer = -1
    return answer

In [ ]:
road="111011110011111011111100011111
n=3
m=0

for r in road:
    if r==0:
        r=1
        m+=1

if m<=n:
    result=len(road)
    