In [7]:
import numpy as np
np.ones((len(board)+1,len(board)+1))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
board_new = np.ones((len(board)+1,len(board)+1))
board_new

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
board_new[:-1,:-1]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
routes = []  # prestep direction, current position x, y
            #route.append()
board = np.array([[0,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,0]])
board_new = np.ones((len(board)+1,len(board)+1))
board_new[:-1,:-1] = board
board_new


array([[0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [1]:
import pprint
pp = pprint.PrettyPrinter( ).pprint

In [38]:
# i by j 블록에서 갈 수 있는 모든 경로의 수
routes = []  # prestep direction, current position x, y
            #route.append()
board = np.array([[0,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,0]])
board_new = np.ones((len(board)+1,len(board)+1))
board_new[:-1,:-1] = board


def findnext(board, routes,i,j):
    if board[i+1,j] == 0 and board[i,j+1] == 1 :
        routes[-1].append([i,j,'down'])
    elif board[i+1,j] == 1 and board[i,j+1] == 0 :
        routes[-1].append([i,j,'right'])
    else :    #둘 다 뚫려있으면
        routes.append(routes[-1])
        routes[-2].append([i,j,'down'])
        routes[-1].append([i,j,'right'])
    return routes


routes.append([0,0,None])
size = len(board[0])

for i in range(size):
    for j in range(size):
        routes = findnext(board_new, routes,i,j)

pp(routes)

[[0,
  0,
  None,
  [0, 0, 'down'],
  [0, 0, 'right'],
  [0, 1, 'down'],
  [0, 2, 'down'],
  [0, 2, 'right'],
  [0, 3, 'down'],
  [1, 0, 'down'],
  [1, 0, 'right'],
  [1, 1, 'right'],
  [1, 2, 'down'],
  [1, 2, 'right'],
  [1, 3, 'down'],
  [1, 3, 'right'],
  [2, 0, 'down'],
  [2, 0, 'right'],
  [2, 1, 'down'],
  [2, 1, 'right'],
  [2, 2, 'down'],
  [2, 3, 'down'],
  [3, 0, 'right'],
  [3, 1, 'right'],
  [3, 2, 'right'],
  [3, 3, 'down'],
  [3, 3, 'right']],
 [0,
  0,
  None,
  [0, 0, 'down'],
  [0, 0, 'right'],
  [0, 1, 'down'],
  [0, 2, 'down'],
  [0, 2, 'right'],
  [0, 3, 'down'],
  [1, 0, 'down'],
  [1, 0, 'right'],
  [1, 1, 'right'],
  [1, 2, 'down'],
  [1, 2, 'right'],
  [1, 3, 'down'],
  [1, 3, 'right'],
  [2, 0, 'down'],
  [2, 0, 'right'],
  [2, 1, 'down'],
  [2, 1, 'right'],
  [2, 2, 'down'],
  [2, 3, 'down'],
  [3, 0, 'right'],
  [3, 1, 'right'],
  [3, 2, 'right'],
  [3, 3, 'down'],
  [3, 3, 'right']],
 [0,
  0,
  None,
  [0, 0, 'down'],
  [0, 0, 'right'],
  [0, 1, 'down'],
 

In [40]:
# i by j 블록에서 갈 수 있는 모든 경로의 수
routes = []  # prestep direction, current position x, y
            #route.append()
board = np.array([[0,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,0]])
board_new = np.ones((len(board)+1,len(board)+1))
board_new[:-1,:-1] = board


def findnext(board, routes,i,j):
    if board[i+1,j] == 0 and board[i,j+1] == 1 :
        routes[-1].append([i+1,j,'down'])
        return routes,i+1,j
    
    elif board[i+1,j] == 1 and board[i,j+1] == 0 :
        routes[-1].append([i,j+1,'right'])
        return routes,i,j+1
    
    elif board[i+1,j] == 1 and board[i,j+1] == 1 :
        del routes[-1]
        return routes,None,None
    
    else :    #둘 다 뚫려있으면
        routes.append(routes[-1])
        routes[-2].append([i+1,j,'down'])
        routes[-1].append([i,j+1,'right'])
        return routes


routes.append([0,0,None])
size = len(board[0])


routes,i,j = findnext(board_new, routes,0,0)    #routes 첫번째
for i in range(size):
    for j in range(size):
        routes,i,j = findnext(board_new, routes,i,j)    #routes 재귀

pp(routes)

[[0,
  0,
  None,
  [1, 1, 'down'],
  [1, 1, 'right'],
  [1, 2, 'down'],
  [1, 3, 'down'],
  [1, 3, 'right'],
  [1, 4, 'down'],
  [2, 1, 'down'],
  [2, 1, 'right'],
  [2, 2, 'right'],
  [2, 3, 'down'],
  [2, 3, 'right'],
  [3, 2, 'down'],
  [3, 2, 'right'],
  [3, 3, 'down'],
  [3, 4, 'down'],
  [4, 1, 'right'],
  [4, 2, 'right'],
  [4, 3, 'right']],
 [0,
  0,
  None,
  [1, 1, 'down'],
  [1, 1, 'right'],
  [1, 2, 'down'],
  [1, 3, 'down'],
  [1, 3, 'right'],
  [1, 4, 'down'],
  [2, 1, 'down'],
  [2, 1, 'right'],
  [2, 2, 'right'],
  [2, 3, 'down'],
  [2, 3, 'right'],
  [3, 2, 'down'],
  [3, 2, 'right'],
  [3, 3, 'down'],
  [3, 4, 'down'],
  [4, 1, 'right'],
  [4, 2, 'right'],
  [4, 3, 'right']],
 [0,
  0,
  None,
  [1, 1, 'down'],
  [1, 1, 'right'],
  [1, 2, 'down'],
  [1, 3, 'down'],
  [1, 3, 'right'],
  [1, 4, 'down'],
  [2, 1, 'down'],
  [2, 1, 'right'],
  [2, 2, 'right'],
  [2, 3, 'down'],
  [2, 3, 'right'],
  [3, 2, 'down'],
  [3, 2, 'right'],
  [3, 3, 'down'],
  [3, 4, 'down'],
  

In [6]:
len(board)

4

In [4]:
import pprint
pp = pprint.PrettyPrinter( ).pprint

import numpy as np
routes = []  # prestep direction, current position x, y
            #route.append()
board = np.array([[0,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,0]])
size = len(board)
board_new = np.ones((size+1,size+1))
board_new[:-1,:-1] = board

def findnext(board, routes,i,j):
    size = len(board)
    if board[i+1,j] == 0 and board[i,j+1] == 1 :
        routes[-1].append([i+1,j,'down'])
    
    elif board[i+1,j] == 1 and board[i,j+1] == 0 :
        routes[-1].append([i,j+1,'right'])
    
    elif board[i+1,j] == 1 and board[i,j+1] == 1 :
        if i==size-1 and j==size-1 :
            return routes
        else :
            del routes[-1]
    
    else :    #둘 다 뚫려있으면
        routes[-1].append([i+1,j,'down'])
        routes.append(routes[-1][:-1])
        routes[-1].append([i,j+1,'right'])
    
    return routes


size = len(board[0])

routes.append([[0,0,None]])
routes = findnext(board_new, routes,0,0)    #routes 첫번째

while True :
    if len(rows_idx) == 0 : continue
    rows_idx = [x[-1][0]for x in routes]
    cols_idx = [x[-1][1]for x in routes]
    if sum(rows_idx)/len(rows_idx) >= size-1 and sum(cols_idx)/len(cols_idx) >= size-1 :
        break
    routes = findnext(board_new, routes, routes[-1][-1][0], routes[-1][-1][1])    #routes 재귀

pp(routes)

KeyboardInterrupt: 

In [41]:
findnext(board_new, routes,0,0)

    

SyntaxError: unexpected EOF while parsing (<ipython-input-41-22fe496861bc>, line 2)

In [18]:
#이건 잘 되는데 아래는 안 될까..
test = [[[0, 0, None]], [[0, 0, None]]]
test[-2].append([1,0,'down'])
test[-1].append([0,1,'right'])
test

[[[0, 0, None], [1, 0, 'down']], [[0, 0, None], [0, 1, 'right']]]

## test

In [3]:
#test= [[[0,0,None]],[[[0,0,None]]]]
test=[]
test.append([[0, 0, None]])


test

[[[0, 0, None]]]

In [4]:
test[-1].append([1,0,'down'])
test

[[[0, 0, None], [1, 0, 'down']]]

In [5]:
test.append(test[-1][:-1])
test

[[[0, 0, None], [1, 0, 'down']], [[0, 0, None]]]

In [6]:
test[-1].append([0,1,'right'])
test

[[[0, 0, None], [1, 0, 'down']], [[0, 0, None], [0, 1, 'right']]]

In [7]:
#re
test[-1].append([1,1,'second'])
test

[[[0, 0, None], [1, 0, 'down']],
 [[0, 0, None], [0, 1, 'right'], [1, 1, 'second']]]

In [8]:
test.append(test[-1][:-1])
test

[[[0, 0, None], [1, 0, 'down']],
 [[0, 0, None], [0, 1, 'right'], [1, 1, 'second']],
 [[0, 0, None], [0, 1, 'right']]]

In [9]:
test[-1].append([0,1,'right'])
test

[[[0, 0, None], [1, 0, 'down']],
 [[0, 0, None], [0, 1, 'right'], [1, 1, 'second']],
 [[0, 0, None], [0, 1, 'right'], [0, 1, 'right']]]

In [10]:
[x[-1][0]for x in test]

[1, 1, 0]

In [11]:
sum([x[-1][0]for x in test])/len([x[-1][0]for x in test])

0.6666666666666666

In [13]:
test[-1]

[[0, 0, None], [0, 1, 'right'], [0, 1, 'right']]

### 재귀함수 재정비

In [14]:
import numpy as np
routes = []  # prestep direction, current position x, y
            #route.append()
board = np.array([[0,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,0]])
size = len(board)
board_new = np.ones((size+1,size+1))
board_new[:-1,:-1] = board

def findnext(board, routes,i,j):
    size = len(board)
    if board[i+1,j] == 0 and board[i,j+1] == 1 :
        routes[-1].append([i+1,j,'down'])
        return [[routes, i+1, j]]
    
    elif board[i+1,j] == 1 and board[i,j+1] == 0 :
        routes[-1].append([i,j+1,'right'])
        return [[routes, i, j+1]]
    
    elif board[i+1,j] == 1 and board[i,j+1] == 1 :
        if i==size-1 and j==size-1 :
            return [[routes, i, j]]
        else :
            del routes[-1]
            return [[routes, i, j]]
    
    else :    #둘 다 뚫려있으면
        routes[-1].append([i+1,j,'down'])
        routes.append(routes[-1][:-1])
        routes[-1].append([i,j+1,'right'])
        return [[routes, i+1, j], [routes, i, j+1]]



def routine(board_new, routes):
    result_temp = findnext(board_new, routes, routes[-1][0], routes[-1][1])
    if len(result_temp) == 1 :
        routes = result_temp
    else :
        routes = result_temp[0]
        routine(board_new, routes)
        
        routes = result_temp[1]
        routine(board_new, routes)
    return routes




size = len(board[0])

routes.append([[0,0,None]])
routes = findnext(board_new, routes,0,0)    #routes 첫번째

while True :
    rows_idx = [x[-1][0]for x in routes]
    cols_idx = [x[-1][1]for x in routes]
    if sum(rows_idx)/len(rows_idx) >= size-1 and sum(cols_idx)/len(cols_idx) >= size-1 :
        break
    
    #routes 재귀
    routes = routine(board_new, routes)

pp(routes)

TypeError: 'int' object is not subscriptable

## all cases 탐색

In [ ]:
import numpy as np
routes = []  # prestep direction, current position x, y
            #route.append()
board = np.array([[0,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,0]])
size = len(board)
board_new = np.ones((size+1,size+1))
board_new[:-1,:-1] = board


def findnext(board, routes,i,j):
    size = len(board)
    if board[i+1,j] == 0 and board[i,j+1] == 1 :
        routes[-1].append([i+1,j,'down'])
        return [[routes, i+1, j]]
    
    elif board[i+1,j] == 1 and board[i,j+1] == 0 :
        routes[-1].append([i,j+1,'right'])
        return [[routes, i, j+1]]
    
    elif board[i+1,j] == 1 and board[i,j+1] == 1 :
        if i==size-1 and j==size-1 :
            return [[routes, i, j]]
        else :
            del routes[-1]
            return [[routes, i, j]]
    
    else :    #둘 다 뚫려있으면
        routes[-1].append([i+1,j,'down'])
        routes.append(routes[-1][:-1])
        routes[-1].append([i,j+1,'right'])
        return [[routes, i+1, j], [routes, i, j+1]]


routes.append([[0,0,None]])
routes = findnext(board_new, routes,0,0)    #routes 첫번째

for i in range(size):
    for j in range(size)

    

while True :
    rows_idx = [x[-1][0]for x in routes]
    cols_idx = [x[-1][1]for x in routes]
    if len(rows_idx) == 0 or len(cols_idx) == 0 : continue
    
    if sum(rows_idx)/len(rows_idx) >= size-1 and sum(cols_idx)/len(cols_idx) >= size-1 :
        break
    
    if routes
    routes = findnext(board_new, routes, routes[-1][-1][0], routes[-1][-1][1])    #routes 재귀

pp(routes)