In [ ]:
def solution(maze):
    answer = 0
    return answer

In [2]:
maze=[[0, 1, 0, 1], [0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0]]

In [17]:
import numpy as np

nsize=len(maze)
maze=np.array(maze)
present=np.array([0,0])
count=[]

In [18]:
maze

array([[0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0]])

In [19]:
maze[0,1]

1

In [20]:
maze[1,0]

0

In [25]:
present=np.array([0,0])
print(present)
present[0]+=1
print(present)

[0 0]
[1 0]


In [27]:
present

array([1, 0])

In [28]:
maze

array([[0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0]])

In [31]:
maze[present[0],present[1]+1]

1

In [5]:
if maze[1,0]==1:
    direction='right'
elif maze[0,1]==1:
    direction='down'



In [ ]:
direcarr=['down','right','up','left']
# 움직이는 방향 우선순위

while present != [nsize, nsize]:
    # elif direc=='right':
    #     # 위 있으면 오른쪽
    #         # 오른쪽도 있으면 아래
    #             #아래도 있으면 왼쪽
    #     #이렇게 네 가지 다 고려해야 함
    #
    #     if maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
    #         direc, present, count = up(direc, present, count)
    #     elif maze[  present[0], present[1]+1  ]!=1:  # 오른쪽 없으면 오른
    #         direc,present,count = right(direc,present,count)
    #     elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
    #         direc, present, count = down(direc, present, count)
    #     elif maze[  present[0], present[1]-1  ]!=1:  #왼 없으면 왼
    #         direc, present, count = left(direc, present, count)


In [33]:
maze

array([[0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0]])

In [50]:
maze=[[0, 1, 0, 1], [0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0]]
maze=np.append(maze, np.ones((1, nsize), dtype=int), 0)
maze=np.append(maze, np.ones((nsize+1,1), dtype=int), 1)

In [51]:
maze

array([[0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [58]:
maze=[[0, 1, 0, 1], [0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0]]
temp=np.ones((nsize+2,nsize+2), dtype=int)
temp[1:-1, 1:-1]=maze
maze=temp

In [59]:
maze

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [34]:
maze

array([[0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0]])

In [6]:
import numpy as np

maze=[[0, 1, 0, 1], [0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0]]
nsize=len(maze)
temp=np.ones((nsize+2,nsize+2), dtype=int)
temp[1:-1, 1:-1]=maze
maze=temp


maze=np.array(maze)
present=np.array([1,1])
count=0

# 처음
if maze[1, 2] == 1:
    direc = 'down'
    present[0]+=1
    count+=1
elif maze[2, 1] == 1:
    direc = 'right'
    present[1]+=1
    count+=1


def right(direc,present,count):
    direc='right'
    present[1] += 1
    count += 1
    return direc,present, count

def left(direc,present,count):
    direc='right'
    present[1] -= 1
    count += 1
    return direc,present, count

def down(direc,present,count):
    direc='down'
    present[0] += 1
    count += 1
    return direc,present, count

def up(direc,present,count):
    direc='up'
    present[0] -= 1
    count += 1
    return direc,present, count


direcarr=['down','right','up','left']
# 움직이는 방향은 다 가능. 왼쪽손에 막혔냐 안 막혔냐


while True:
    if present[0]==nsize and present[1]==nsize:
        break
        
    if direc=='down':
        if maze[  present[0], present[1]+1  ]!=1:  # 오른쪽 없으면 오른
            direc,present,count = right(direc,present,count)
        elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
            direc, present, count = down(direc, present, count)
        elif maze[  present[0], present[1]-1  ]!=1:  #왼 없으면 왼
            direc, present, count = left(direc, present, count)
        elif maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위
            direc, present, count = up(direc, present, count)

    elif direc=='right':
        if maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
            direc, present, count = up(direc, present, count)
        elif maze[  present[0], present[1]+1  ]!=1:  # 오른 없으면 오른
            direc,present,count = right(direc,present,count)
        elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
            direc, present, count = down(direc, present, count)
        elif maze[present[0], present[1] - 1] != 1:  # 왼 없으면 왼
            direc, present, count = left(direc, present, count)


    elif direc=='up':
        if maze[present[0], present[1] - 1] != 1:  # 왼 없으면 왼
            direc, present, count = left(direc, present, count)
        elif maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
            direc, present, count = up(direc, present, count)
        elif maze[  present[0], present[1]+1  ]!=1:  # 오른 없으면 오른
            direc,present,count = right(direc,present,count)
        elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
            direc, present, count = down(direc, present, count)


    elif direc=='left':
        if maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
            direc, present, count = down(direc, present, count)
        elif maze[present[0], present[1] - 1] != 1:  # 왼 없으면 왼
            direc, present, count = left(direc, present, count)
        elif maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
            direc, present, count = up(direc, present, count)
        elif maze[  present[0], present[1]+1  ]!=1:  # 오른 없으면 오른
            direc,present,count = right(direc,present,count)
    print("present>>{}, direc:{}, count:{}".format(present,direc,count))

present>>[3 1], direc:down, count:2
present>>[3 2], direc:right, count:3
present>>[3 3], direc:right, count:4
present>>[2 3], direc:up, count:5
present>>[1 3], direc:up, count:6
present>>[2 3], direc:down, count:7
present>>[2 4], direc:right, count:8
present>>[3 4], direc:down, count:9
present>>[4 4], direc:down, count:10


In [15]:
def solution(maze):
    import numpy as np
    nsize=len(maze)
    maze=np.array(maze)
    temp=np.ones((nsize+2,nsize+2), dtype=int)
    temp[1:-1, 1:-1]=maze
    maze=temp
    
    present=np.array([1,1])
    count=0
    
    # 처음
    if maze[1, 2] == 1:
        direc = 'down'
        present[0]+=1
        count+=1
    elif maze[2, 1] == 1:
        direc = 'right'
        present[1]+=1
        count+=1
    
    
    def right(direc,present,count):
        direc='right'
        present[1] += 1
        count += 1
        return direc,present, count
    
    def left(direc,present,count):
        direc='left'
        present[1] -= 1
        count += 1
        return direc,present, count
    
    def down(direc,present,count):
        direc='down'
        present[0] += 1
        count += 1
        return direc,present, count
    
    def up(direc,present,count):
        direc='up'
        present[0] -= 1
        count += 1
        return direc,present, count
    
    
    direcarr=['down','right','up','left']
    # 움직이는 방향은 다 가능. 왼쪽손에 막혔냐 안 막혔냐
    
    while True:
        if present[0]==nsize and present[1]==nsize:
            break

        if direc=='down':
            if maze[  present[0], present[1]+1  ]!=1:  # 오른쪽 없으면 오른
                direc,present,count = right(direc,present,count)
            elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
                direc, present, count = down(direc, present, count)
            elif maze[  present[0], present[1]-1  ]!=1:  #왼 없으면 왼
                direc, present, count = left(direc, present, count)
            elif maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위
                direc, present, count = up(direc, present, count)
    
        elif direc=='right':
            if maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
                direc, present, count = up(direc, present, count)
            elif maze[  present[0], present[1]+1  ]!=1:  # 오른 없으면 오른
                direc,present,count = right(direc,present,count)
            elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
                direc, present, count = down(direc, present, count)
            elif maze[present[0], present[1] - 1] != 1:  # 왼 없으면 왼
                direc, present, count = left(direc, present, count)
    
    
        elif direc=='up':
            if maze[present[0], present[1] - 1] != 1:  # 왼 없으면 왼
                direc, present, count = left(direc, present, count)
            elif maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
                direc, present, count = up(direc, present, count)
            elif maze[  present[0], present[1]+1  ]!=1:  # 오른 없으면 오른
                direc,present,count = right(direc,present,count)
            elif maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
                direc, present, count = down(direc, present, count)
    
    
        elif direc=='left':
            if maze[  present[0]+1, present[1]  ]!=1:  # 아래 없으면 아래
                direc, present, count = down(direc, present, count)
            elif maze[present[0], present[1] - 1] != 1:  # 왼 없으면 왼
                direc, present, count = left(direc, present, count)
            elif maze[  present[0]-1, present[1]  ]!=1:  # 위 없으면 위로
                direc, present, count = up(direc, present, count)
            elif maze[  present[0], present[1]+1  ]!=1:  # 오른 없으면 오른
                direc,present,count = right(direc,present,count)

        print("present>>{}, direc:{}, count:{}".format(present,direc,count))
    answer = count
    return answer

In [16]:
solution([[0, 1, 0, 1], [0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0]])

present>>[3 1], direc:down, count:2
present>>[3 2], direc:right, count:3
present>>[3 3], direc:right, count:4
present>>[2 3], direc:up, count:5
present>>[1 3], direc:up, count:6
present>>[2 3], direc:down, count:7
present>>[2 4], direc:right, count:8
present>>[3 4], direc:down, count:9
present>>[4 4], direc:down, count:10


10

In [17]:
solution([[0, 1, 0, 0, 0, 0], [0, 1, 0, 1, 1, 0], [0, 1, 0, 0, 1, 0], [0, 1, 1, 1, 1, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 1, 0]])

present>>[3 1], direc:down, count:2
present>>[4 1], direc:down, count:3
present>>[5 1], direc:down, count:4
present>>[6 1], direc:down, count:5
present>>[6 2], direc:right, count:6
present>>[6 3], direc:right, count:7
present>>[5 3], direc:up, count:8
present>>[5 4], direc:right, count:9
present>>[5 5], direc:right, count:10
present>>[5 6], direc:right, count:11
present>>[4 6], direc:up, count:12
present>>[3 6], direc:up, count:13
present>>[2 6], direc:up, count:14
present>>[1 6], direc:up, count:15
present>>[1 5], direc:left, count:16
present>>[1 4], direc:left, count:17
present>>[1 3], direc:left, count:18
present>>[2 3], direc:down, count:19
present>>[3 3], direc:down, count:20
present>>[3 4], direc:right, count:21
present>>[3 3], direc:left, count:22
present>>[2 3], direc:up, count:23
present>>[1 3], direc:up, count:24
present>>[1 4], direc:right, count:25
present>>[1 5], direc:right, count:26
present>>[1 6], direc:right, count:27
present>>[2 6], direc:down, count:28
present>>[3 6]

32

In [18]:
solution([[0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0]])

present>>[2 2], direc:right, count:2
present>>[3 2], direc:down, count:3
present>>[3 3], direc:right, count:4
present>>[4 3], direc:down, count:5
present>>[4 4], direc:right, count:6
present>>[5 4], direc:down, count:7
present>>[5 5], direc:right, count:8
present>>[5 6], direc:right, count:9
present>>[4 6], direc:up, count:10
present>>[3 6], direc:up, count:11
present>>[3 5], direc:left, count:12
present>>[2 5], direc:up, count:13
present>>[2 4], direc:left, count:14
present>>[1 4], direc:up, count:15
present>>[1 3], direc:left, count:16
present>>[1 4], direc:right, count:17
present>>[1 5], direc:right, count:18
present>>[1 6], direc:right, count:19
present>>[2 6], direc:down, count:20
present>>[3 6], direc:down, count:21
present>>[4 6], direc:down, count:22
present>>[5 6], direc:down, count:23
present>>[6 6], direc:down, count:24


24

In [19]:
solution([[0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 1, 1], [0, 0, 0, 0, 0, 0], [1, 0, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0], [1, 1, 0, 1, 1, 0]])

present>>[1 3], direc:right, count:2
present>>[1 4], direc:right, count:3
present>>[1 5], direc:right, count:4
present>>[1 6], direc:right, count:5
present>>[1 5], direc:left, count:6
present>>[1 4], direc:left, count:7
present>>[2 4], direc:down, count:8
present>>[3 4], direc:down, count:9
present>>[3 5], direc:right, count:10
present>>[3 6], direc:right, count:11
present>>[3 5], direc:left, count:12
present>>[3 4], direc:left, count:13
present>>[3 3], direc:left, count:14
present>>[3 2], direc:left, count:15
present>>[4 2], direc:down, count:16
present>>[5 2], direc:down, count:17
present>>[5 3], direc:right, count:18
present>>[5 4], direc:right, count:19
present>>[5 5], direc:right, count:20
present>>[5 6], direc:right, count:21
present>>[6 6], direc:down, count:22


22