# Programmers

## 스택큐 - 다리를 지나는 트럭

hard

### numpy

In [2]:
import numpy as np

In [12]:
truck_weights = [7,4,5,6]
queue = []
t=0



In [1]:
truck_weights = [7,4,5,6]
bridge_length = 2
weight = 10

In [10]:
t=0
# current = [truck_weights,[0]*len(truck_weights)]
current = [[],[]]

for i in range(len(truck_weights)):
    myw = truck_weights[i]
        while True:
            #현재 트럭 전체
            if np.sum(current, axis=1)[0] + myw <= weight:
                current[0].append(myw)
                current[1].append(0)
                
            if current[1][i] <= bridge_length:
                current[0][i] = 0
                current[1][i] +=1
                t+=1
            else:
                    
            else:
                break

In [11]:
print(t)

0


In [13]:
current = [[7,4,5,6],[0,1,2,3]]

In [21]:
np.sum(current, axis=1)

array([22,  6])

In [22]:
truck_weights = [7,4,5,6]
bridge_length = 2
weight = 10

In [43]:
# numpy 사용

table = np.zeros((1,bridge_length))

t=0
i=0
# table = np.append(table, [[0]*bridge_length], axis=0)

for i in range(len(truck_weights)):
    while True:
        myw = truck_weights[i]

        if np.sum(table, axis=1)[-1]  + myw > weight:
            t+=1
            table = np.append(table, [[0]*bridge_length], axis=0); table[t,i] = myw

        else :
            t+=1
            table = np.append(table, [[0]*bridge_length], axis=0); table[t,i] = myw
            i+=1
        print(table)
        break

[[0. 0.]
 [1. 0.]]


In [45]:
aa = np.array([[1,2],[3,4]])
aa

array([[1, 2],
       [3, 4]])

In [49]:
np.sum(aa,axis=0)[0]

4

In [43]:
# cache 사용

In [55]:
t=0
i=0
# temp=np.array([])

t+=1
temp=np.array([truck_weights[t-1],1])

i+=1

In [56]:
temp

array([7, 1])

In [ ]:
# for idx, w in enumerate(truck_weights):
while True:
    myw = truck_weights[i]
    if sum(temp)  + myw > weight:
        t+=1
    i+=1

In [87]:
truck_weights = [7,4,5,6]
bridge_length = 2
weight = 10

In [98]:
i=0
t=0
queue = [0]*bridge_length

while True:
    if sum(queue)==0 and i>0:
        print('time',t)
        break
    try:
        myw = truck_weights[i]
    except:
        myw=0
    
    
    
    if sum(queue[:-1])+myw > weight:
        queue[1:]=queue[:-1]
        queue[0]=0
        t+=1
        print('q',queue)
        print('over',t,i)
    else:
        queue[1:]=queue[:-1]
        queue[0]=myw
        t+=1
        i+=1
        print('q',queue)
        print('in',t,i)

q [7, 0]
in 1 1
q [0, 7]
over 2 1
q [4, 0]
in 3 2
q [5, 4]
in 4 3
q [0, 5]
over 5 3
q [6, 0]
in 6 4
q [0, 6]
in 7 5
q [0, 0]
in 8 6
time 8


In [ ]:
queue[1:]

In [69]:
aa = [7,4,5,6]

In [70]:
aa[1:]

[4, 5, 6]

In [71]:
aa[:-1]

[7, 4, 5]

### list

In [ ]:
# array (queue) 이용

In [100]:
import numpy as np

def solution(bridge_length, weight, truck_weights):
    i=t=0
    queue = [0]*bridge_length
    
    while True:
        if sum(queue)==0 and i>0:
            return t
        try:
            myw = truck_weights[i]
        except:
            myw=0



        if sum(queue[:-1])+myw > weight:
            queue[1:]=queue[:-1]
            queue[0]=0
            t+=1
        else:
            queue[1:]=queue[:-1]
            queue[0]=myw
            t+=1
            i+=1
    return 0


In [102]:
solution(2,10,[7,4,5,6])

8

In [103]:
solution(100,100,[10])

101

In [105]:
solution(100,100,[10,10,10,10,10,10,10,10,10,10])

110

결과

테스트 1 〉	통과 (90.03ms, 28.2MB)
테스트 2 〉	통과 (7224.39ms, 28.4MB)
테스트 3 〉	통과 (0.17ms, 28.5MB)
테스트 4 〉	통과 (1369.63ms, 28.3MB)
테스트 5 〉	실패 (시간 초과)
테스트 6 〉	통과 (6670.07ms, 28.3MB)
테스트 7 〉	통과 (30.03ms, 28.1MB)
테스트 8 〉	통과 (0.76ms, 28.5MB)
테스트 9 〉	통과 (14.35ms, 28.1MB)
테스트 10 〉	통과 (0.87ms, 28MB)
테스트 11 〉	통과 (0.07ms, 28.2MB)
테스트 12 〉	통과 (0.63ms, 28.3MB)
테스트 13 〉	통과 (5.68ms, 28.2MB)
테스트 14 〉	통과 (0.36ms, 28.4MB)

In [ ]:
# sum 하나 줄임

In [ ]:
import numpy as np

def solution(bridge_length, weight, truck_weights):
    i=t=0
    queue = [0]*bridge_length
    
    while True:
        qsum = sum(queue)
        
        if qsum==0 and i>0:
            return t
        
        try:
            myw = truck_weights[i]
        except:
            myw=0
            
            
            
        if qsum - queue[-1]+myw > weight:
            queue[1:]=queue[:-1]
            queue[0]=0
            t+=1
        else:
            queue[1:]=queue[:-1]
            queue[0]=myw
            t+=1
            i+=1
    return 0


테스트 1 〉	통과 (51.87ms, 27.7MB)
테스트 2 〉	통과 (4136.03ms, 28.2MB)
테스트 3 〉	통과 (0.13ms, 28.2MB)
테스트 4 〉	통과 (786.07ms, 28.2MB)
테스트 5 〉	실패 (시간 초과)
테스트 6 〉	통과 (3828.89ms, 28.4MB)
테스트 7 〉	통과 (17.25ms, 28.1MB)
테스트 8 〉	통과 (0.51ms, 28MB)
테스트 9 〉	통과 (9.14ms, 28.1MB)
테스트 10 〉	통과 (0.57ms, 28.3MB)
테스트 11 〉	통과 (0.06ms, 28.1MB)
테스트 12 〉	통과 (0.46ms, 27.8MB)
테스트 13 〉	통과 (3.49ms, 28.3MB)
테스트 14 〉	통과 (0.25ms, 28.4MB)

In [106]:
# 리스트 계산 조금 바꾼

In [ ]:
import numpy as np

def solution(bridge_length, weight, truck_weights):
    i=t=0
    queue = [0]*bridge_length
    
    while True:
        qsum = sum(queue)
        
        if qsum==0 and i>0:
            return t
        
        try:
            myw = truck_weights[i]
        except:
            myw=0
            
            
            
        if qsum - queue[-1]+myw > weight:
            queue = [0]+queue[:-1]
            t+=1
        else:
            queue = [myw]+queue[:-1]
            t+=1
            i+=1
    return 0

테스트 1 〉	통과 (53.24ms, 28.2MB)
테스트 2 〉	통과 (4218.55ms, 28.3MB)
테스트 3 〉	통과 (0.12ms, 28.4MB)
테스트 4 〉	통과 (803.02ms, 28.2MB)
테스트 5 〉	실패 (시간 초과)
테스트 6 〉	통과 (3899.01ms, 28MB)
테스트 7 〉	통과 (17.83ms, 27.9MB)
테스트 8 〉	통과 (0.48ms, 28.2MB)
테스트 9 〉	통과 (9.15ms, 28.2MB)
테스트 10 〉	통과 (0.55ms, 28.4MB)
테스트 11 〉	통과 (0.06ms, 28.3MB)
테스트 12 〉	통과 (0.43ms, 28.1MB)
테스트 13 〉	통과 (3.49ms, 28.5MB)
테스트 14 〉	통과 (0.28ms, 28MB)

In [ ]:
# 리스트 계산 조금 바꾼2

In [107]:
import numpy as np

def solution(bridge_length, weight, truck_weights):
    i=t=0
    queue = [0]*bridge_length
    
    while True:
        qsum = sum(queue)
        
        if qsum==0 and i>0:
            return t
        
        try:
            myw = truck_weights[i]
        except:
            myw=0
            
            
            
        if qsum - queue[-1]+myw > weight:
            del queue[-1]
            queue = [0]+queue
            t+=1
        else:
            del queue[-1]
            queue = [myw]+queue
            t+=1
            i+=1
    return 0

테스트 1 〉	통과 (39.32ms, 28.1MB)
테스트 2 〉	통과 (3118.44ms, 28.6MB)
테스트 3 〉	통과 (0.12ms, 28.5MB)
테스트 4 〉	통과 (596.42ms, 28.2MB)
테스트 5 〉	실패 (시간 초과)
테스트 6 〉	통과 (2887.33ms, 28.3MB)
테스트 7 〉	통과 (13.40ms, 28MB)
테스트 8 〉	통과 (0.40ms, 28.3MB)
테스트 9 〉	통과 (7.73ms, 28MB)
테스트 10 〉	통과 (0.48ms, 28.2MB)
테스트 11 〉	통과 (0.06ms, 28.3MB)
테스트 12 〉	통과 (0.39ms, 28.3MB)
테스트 13 〉	통과 (2.77ms, 28.3MB)
테스트 14 〉	통과 (0.21ms, 28.1MB)

In [116]:
aa = [1,2,3,4,5]
aa[:3][::-1]

[3, 2, 1]

In [122]:
aa[5-3:]

[3, 4, 5]

In [ ]:
#잘못바꾼듯.

In [123]:
import numpy as np

def solution(bridge_length, weight, truck_weights):
    i=t=0
    queue = [0]*bridge_length
    
    fst = len(truck_weights)//3
    if sum(truck_weights[:fst]) < weight :
        queue[len(queue)-fst:] = truck_weights[:fst][::-1]
        i += fst
    
    
    
    while True:
        qsum = sum(queue)
        
        if qsum==0 and i>0:
            return t
        
        try:
            myw = truck_weights[i]
        except:
            myw=0
            
            
            
        if qsum - queue[-1]+myw > weight:
            del queue[-1]
            queue = [0]+queue
            t+=1
        else:
            del queue[-1]
            queue = [myw]+queue
            t+=1
            i+=1
    return 0

### queue

In [124]:
# queue FIFO

In [150]:
from collections import deque
qu = deque()

In [151]:
qu.append(7)
qu.append(6)

In [152]:
qu[-1]

6

In [154]:
aa = qu.popleft()

In [155]:
qu

deque([6])

In [156]:
aa

7

In [161]:
deque([0])

deque([0])

In [198]:
from collections import deque

def solution(bridge_length, weight, truck_weights):
    i=t=0
    qsum = 0
    qu = deque([0]*bridge_length,maxlen=bridge_length)
    
    
    
    while True:
        
        if qsum==0 and i>0:
            return t
        
        try:
            myw = truck_weights[i]
        except:
            myw=0
        
        temp = qsum+myw-qu[0]
        if temp > weight:
            qsum=qsum+0-qu[0]
            qu.append(0)
            t+=1
        else:
            qsum=qsum+myw-qu[0]
            qu.append(myw)
            t+=1
            i+=1
    return 0

In [199]:
solution(2,10,[7,4,5,6])

8

테스트 1 〉	통과 (1.05ms, 10.8MB)
테스트 2 〉	통과 (12.29ms, 10.8MB)
테스트 3 〉	통과 (0.07ms, 10.7MB)
테스트 4 〉	통과 (8.81ms, 10.6MB)
테스트 5 〉	통과 (76.03ms, 10.8MB)
테스트 6 〉	통과 (23.83ms, 10.7MB)
테스트 7 〉	통과 (0.67ms, 10.8MB)
테스트 8 〉	통과 (0.16ms, 10.7MB)
테스트 9 〉	통과 (2.87ms, 10.8MB)
테스트 10 〉	통과 (0.16ms, 10.6MB)
테스트 11 〉	통과 (0.04ms, 10.6MB)
테스트 12 〉	통과 (0.23ms, 10.8MB)
테스트 13 〉	통과 (0.78ms, 10.7MB)
테스트 14 〉	통과 (0.08ms, 10.8MB)