## 9.6. 부녀회장이 될테야
- 문제

평소 반상회에 참석하는 것을 좋아하는 주희는 이번 기회에 부녀회장이 되고 싶어 각 층의 사람들을 불러 모아 반상회를 주최하려고 한다.

이 아파트에 거주를 하려면 조건이 있는데, “a층의 b호에 살려면 자신의 아래(a-1)층의 1호부터 b호까지 사람들의 수의 합만큼 사람들을 데려와 살아야 한다” 는 계약 조항을 꼭 지키고 들어와야 한다.

아파트에 비어있는 집은 없고 모든 거주민들이 이 계약 조건을 지키고 왔다고 가정했을 때, 주어지는 양의 정수 k와 n에 대해 k층에 n호에는 몇 명이 살고 있는지 출력하라. 단, 아파트에는 0층부터 있고 각층에는 1호부터 있으며, 0층의 i호에는 i명이 산다.

- 입력

첫 번째 줄에 Test case의 수 T가 주어진다. 그리고 각각의 케이스마다 입력으로 첫 번째 줄에 정수 k, 두 번째 줄에 정수 n이 주어진다. (1 <= k <= 14, 1 <= n <= 14)

- 출력

각각의 Test case에 대해서 해당 집에 거주민 수를 출력하라.

In [6]:
import numpy as np

In [2]:
t=int(input())
for _ in range(t):
    k,n=[int(input()) for _ in range(2)]
print(t,k,n)

1
2
3
1 2 3


In [7]:
#for _ in range(int(input())):
def tabl():
#    k,n=[int(input()) for _ in range(2)]
    f=[[]*14]
    f[0]=[i for i in range(1,14)]
    for k in range(1,14):
        for n in range(1,14):
            temp=[]
            temp.append(sum(f[k-1][:n]))
        f[k].append(temp)
    return f
    

print(tabl())

IndexError: list index out of range

In [8]:
print([[7]*14])

[[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]]


In [9]:
f=np.zeros((14,14))
f[0,:]=[i for i in range(1,14)]

ValueError: cannot copy sequence with size 13 to array axis with dimension 14

In [10]:
f=np.zeros((14,13))
f[0,:]=[i+1 for i in range(13)]
f[:,0]=1
sum(f[0][0:2])


3.0

In [14]:
# table 전체를 만드는 것. 그러나 시간계산 오래걸림.
import numpy as np
def tabl(n,m):
    f=np.zeros((n+1,m))
    f[0,:]=[i+1 for i in range(m)]
    f[:,0]=1
    for i in range(1,n+1):
        for j in range(1,m):
            f[i,j]=int(sum(f[i-1][0:j+1]))
    
    return f  #np.sort(f,axis=0)[::-1]
print(tabl(2,3))

[[ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 1.  4. 10.]]


In [17]:
#런타임 에러
import numpy as np
def tabl(n,m):
    f=np.zeros((n+1,m))
    f[0,:]=[i+1 for i in range(m)]
    f[:,0]=1
    for i in range(1,n+1):
        for j in range(1,m):
            f[i,j]=int(sum(f[i-1][0:j+1]))
    return int(f[n,m-1])

for _ in range(int(input())):
    k=int(input())
    n=int(input())
    print(tabl(k,n))

2
1
3
6
2
3
10


In [18]:
tabl(4,5)

126